name: Build Solution on Windows

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches:
      - master      
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    # Specify Windows as the target OS
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Specify your .NET
