name: Build and Test Solution on Windows

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches:
      - master      
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    # Specify Windows as the target OS
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Specify your .NET version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # Step 5: Run tests
      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --verbosity normal
